server:
  port: 9191

spring:
  application:
    name: OLX-API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: OLX-ADVERTISES
            uri: lb://OLX-ADVERTISES
            predicates:
            - Path=/olx-advertise/**, /olx-advertise/v3/api-docs
          - id: OLX-LOGIN
            uri: lb://OLX-LOGIN
            predicates:
            - Path=/user-management/**, /user-management/v3/api-docs
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: gateway-service
      - url: /olx-advertise/v3/api-docs
        name: olx-advertise
      - url: /user-management/v3/api-docs
        name: user-management
